### ISSUE TITLE
KDE Plasma support

### ISSUE THREAD

**Issue by giswqs** [jahnf/Projecteur#5] opened 2019-03-10 04:20 UTC
Thank you for developing this! I am trying to get Spotlight working in Manjaro Linux. I followed the steps to build and install it without any problem. However, the application does not show up in the system tray. Any suggestions?

**Comment by jahnf** [comment] 2019-03-10 04:30
To be honest until now I never heard of Manjaro Linux. What desktop environment are you using it with? Xfce, KDE, Gnome...?

**Comment by giswqs** [comment] 2019-03-10 04:48
Manjaro Linux has become quite popular over the past two years (see [distrowatch.com](https://distrowatch.com/)). I am using Manjaro [KDE](https://manjaro.org/download/kde/) with [QT 5.12.1](https://wiki.qt.io/Qt_5.12_Release)

**Comment by jahnf** [comment] 2019-03-10 05:03
Good to know I'll have to check it out one day :) 
Also thank you for posting this issue.
I use the "QSystemTrayIcon" from the Qt Framework to create a system tray icon. - I'll have to reproduce the issue with KDE in the next few days (in a VM , since all my machines have Gnome)
Interesting that the problem is with KDE, which itself based on a lot of Qt :)

**Comment by jahnf** [comment] 2019-03-15 05:16
Hey - so as it turns out the system tray icon is there on Manjaro KDE edition, but it's under _"Status and Notifications"_ as you see in the screenshot. If you right click on "Projecteur" there you will get the context menu.
![manjaro-kde-screenshot](https://user-images.githubusercontent.com/5852240/54409919-838eaa00-46e9-11e9-81d3-014dcd100d16.png)
![Screenshot from 2019-03-15 06-09-30](https://user-images.githubusercontent.com/5852240/54409979-c51f5500-46e9-11e9-85dc-ae3bafd1bcb6.png)

**Comment by giswqs** [comment] 2019-03-15 12:24
Many thanks for taking the time to test it on Manjaro KDE. I am able to see the Projecteur on system tray now. However, the spotlight does not seem to work properly. See below. It only shows up in a smaller area. When the presentation is full screen mode, the spotlight does not work. I tested it on both my laptop and desktop computers. The same issue exists. Any suggestions? Thanks. 

![Imgur](https://i.imgur.com/6i4mYNk.png)

**Comment by maehne** [comment] 2019-03-15 13:18
> Many thanks for taking the time to test it on Manjaro KDE. I am able to see the Projecteur on system tray now. However, the spotlight does not seem to work properly. See below. It only shows up in a smaller area. When the presentation is full screen mode, the spotlight does not work. I tested it on both my laptop and desktop computers. The same issue exists. Any suggestions? Thanks.
> 
> ![Imgur](https://camo.githubusercontent.com/83a7add7c9e312751fd5f3cb072f3926e16e8ae1/68747470733a2f2f692e696d6775722e636f6d2f3669346d594e6b2e706e67)

I have observed the same behaviour while testing projecteur on the [KDE Plasma Desktop 5.12 on Debian 9](
https://neptuneos.com/de/news-reader/upgrade-debian-9s-plasma-5-8-zu-neptunes-plasma-5-12.html).

**Comment by jahnf** [comment] 2019-03-15 13:35
Thanks for the feedback. Seems like in KDE the size and positioning of the transparent spotlight window is wrong. I will need to investigate.

**Comment by jahnf** [comment] 2019-03-15 18:42
@giswqs @maehne Could you please give it a try with the latest version from develop?
(If you have a multi-monitor setup: Could you please also check setting/switching of the monitor for the spotlight?)

**Comment by giswqs** [comment] 2019-03-15 19:13
I just tested the latest version on a single-screen laptop and a multi-monitor desktop. The size issue seems fixed. The spotlight now can move freely on the screen. However, when the PPT is in full-screen mode, the spotlight does not work. Thanks.

**Comment by maehne** [comment] 2019-03-16 09:41
@jahnf: Thanks for addressing the issue! I currently don't have access to the respective machine as I am travelling. I will test it once I am back.

**Comment by jahnf** [comment] 2019-03-18 13:57
The issue with the Libre Office Impress full screen presentation is reproducible in a Manjaro KDE virtual machine.. Unfortunately the spotlight window seems to be behind the impress presentation window... I have a vague idea on how to implement a work around to force the spotlight window to the top even in this situation (might involves some trial and error...)

**Comment by giswqs** [comment] 2019-03-18 14:10
I primarily use Google Slides for presentation, but I did test spotlight with both Google Slides and LibreOffice Impress. Many thanks for your time!

**Comment by maehne** [comment] 2019-04-20 16:18
I have tested the latest version of Projecteur from development HEAD (84ae857) on KDE Plasma desktop 5.14.5 coming with Debian Buster. It works correctly on one of the two screens on the normal Plasma desktop when the unifying receiver is used to connect to the SPOTLIGHT presenter. However, neither the Spotlight nor Center Dot is displayed when in presentation mode of Libreoffice Presenter nor Okular (for PDF slides) nor PDF presenter console (pdfpc).

The correctly working external LCD screen has a resolution of 3840x1080 (32:9 ratio). On the laptop screen with different resolution 2560x1440 (16:9 ratio), the spotlight effect does not cover the full screen. It seems that the resolution of the other screen is used to draw the darkened area leaving the top and bottom in the original color and also a part of the external screen is darkened.

I also noticed another minor GUI glitch: When clicking on the Projecteur icon with the left button, the context menu appears on the top left corner of the screen instead near the mouse cursor (as is the case if you do the click with the right mouse button). How about opening directly the Preferences window when clicking with the left mouse button and showing the context menu when clicking with the right button?

**Comment by jahnf** [comment] 2019-04-21 06:11
Thanks @maehne for the detailed description and test - this helps a lot . In May I'll have again more time to work on Projecteur. Other than that, contributions are always welcome.

**Comment by jahnf** [comment] 2019-05-06 16:44
@maehne @giswqs  - I still need to do tests with multi-monitor setups, but the KDE issue with the spot not showing over full screen presentation windows should be fixed. If you could do a quick check to verify would be very helpful. 

- There is still a minor issue when opening the preferences once - the spot window will not cover the whole screen but the whole screen minus where the task bar is... I will address this separately.

**Comment by maehne** [comment] 2019-05-06 17:10
@jahnf: Thanks for addressing this issue! I can confirm that now the spot is consistently showing on top of the full screen presentation windows of Libreoffice Presenter, Okular, and pdfpc. However, the spot is restrained to a single monitor now, i.e., the spot won't follow the mouse to a second screen. Anyway, it makes the Spotlight device on KDE Plasma desktop environment already much more useful!

**Comment by jahnf** [comment] 2019-05-06 17:19
@maehne : Thanks for testing. The way it's implemented, the spot does not follow the mouse over screen boundaries currently, but will only show on the configured screen set in the preferences dialog. Which in most cases would be probably the second screen or beamer where the presentation is showing. At least that was my thought when first implementing it.

**Comment by maehne** [comment] 2019-05-06 17:26
Thanks for explaining the intended behaviour. However, I can set the screen in the Prefences dialogue to whichever value I want and the spotlight is still displayed on screen 0 (in my case an external HDMI monitor) and never on screen 1 (my laptop screen). The official Spotlight app on macOS and Windows follows the mouse cursor, i.e., the screen shows a spotlight, where the mouse cursor currently is. Also showing the spotlight, it is possible to move between screens. I don't need that latter functionality, but I think it would be more intuitive if the spotlight is always shown on the screen, where the mouse cursor is currently (shown or hidden).

**Comment by jahnf** [comment] 2019-05-06 18:13
Yes, so it seems that switching the screen does not work in KDE as it does on GNOME. For now as a workaround you can try to move the preferences dialog box to the screen where you wish to have the spot and then set it with the combo box (maybe back and forth).

**Comment by maehne** [comment] 2019-05-06 18:18
Yes, moving the Prefences dialogue to the laptop screen works. The screen combo box has no influence on the behaviour. Also, the greyed out area still covers only the central part of the laptop screen and corresponds from its dimensions to the size of my external screen.

**Comment by jahnf** [comment] 2019-05-07 16:03
@maehne Replaced the automatic preview in the back of the preferences dialog with a simple test button.. Makes things more stable and much easier. Behavior with the screen is still the same: The spotlight will still only show on the monitor set in the preferences. If it would follow the mouse that would be nice, but I will create a separate feature issue for that.  

If you have a minute, please give the latest version from develop a try

**Comment by jahnf** [comment] 2019-05-08 04:47
Tested at a co-worker's machine with KDE, looks like its working

**Closed by jahnf** 2019-05-08 04:47 UTC
Labels: bug
