### ISSUE TITLE
[BUG] Compilation will fail without installed Git

### ISSUE THREAD

**Issue by ConiKost** [jahnf/Projecteur#73] opened 2020-05-10 16:10 UTC
**Description**
FAILED: CMakeFiles/projecteur.dir/version/projecteur/projecteur-GitVersion.cc.o
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -DCXX_COMPILER_ID=GNU -DCXX_COMPILER_VERSION=9.3.0 -DHAS_Qt5_DBus=1 -DHAS_Qt5_X11Extras=1 -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -Iprojecteur_autogen/include -I/var/tmp/portage/x11-misc/projecteur-0.7/work/Projecteur-0.7/src -Iversion/projecteur -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtQmlModels -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtDBus  -march=native -mfpmath=sse,387 -mtune=intel -O3 -frecord-gcc-switches -fomit-frame-pointer -malign-data=abi -mtls-dialect=gnu2 -pipe -fvisibility-inlines-hidden   -Wall -Wextra -fPIC -std=gnu++14 -MD -MT CMakeFiles/projecteur.dir/version/projecteur/projecteur-GitVersion.cc.o -MF CMakeFiles/projecteur.dir/version/projecteur/projecteur-GitVersion.cc.o.d -o CMakeFiles/projecteur.dir/version/projecteur/projecteur-GitVersion.cc.o -c version/projecteur/projecteur-GitVersion.cc
version/projecteur/projecteur-GitVersion.cc: In function ‘unsigned int projecteur::version_distance()’:
version/projecteur/projecteur-GitVersion.cc:9:37: error: return-statement with no value, in function returning ‘unsigned int’ [-fpermissive]
    9 |   unsigned int version_distance() { return ; }
      |                                     ^~~~~~

**To Reproduce**
1) Download release
2) Don't have installed git
3) Compilation will fail

**Expected behavior**
1) Compilation will work without installed Git

**Comment by jahnf** [comment] 2020-05-10 16:25
Hi thanks for the report,

I can confirm that. I checked it quickly in a docker container. Seems to be a regression, compiling without git worked at one point :)

I'm looking into it. In the meanwhile you can use the CI created souce release file also listed under the release:
* https://github.com/jahnf/Projecteur/releases/download/v0.7/projecteur-0.7_source.tar.gz
instead of the one that is failing (https://github.com/jahnf/Projecteur/archive/v0.7.tar.gz)

**Comment by jahnf** [comment] 2020-05-10 18:47
Version generation should be fixed when building exported git archives or without having git installed for all future versions.

**Closed by jahnf** 2020-05-10 18:47 UTC
Labels: bug, build-system

**Comment by ConiKost** [comment] 2020-05-10 19:33
Thanks!
