### ISSUE TITLE
[BUG] Wrong key-press captured when Shift is used (Input-Mapping)

### ISSUE THREAD

**Issue by jschildgen** [jahnf/Projecteur#189] opened 2022-08-15 08:22 UTC
**Description**
In the Input-Mapping dialogue, Input Sequences can be mapped to a key press. When this key-press contains Shift, it does not correctly capture the key sequence. 

**To Reproduce**
Add a new input sequence, choose "Key Sequence" and press the keys Alt Shift 1, it is captured as Alt Shift 2

**Expected behavior**
In the video-streaming software OBS Studio, I can switch between scenes with keyboard shortcuts. I set up the hotkeys Alt Shift 1, Alt Shift 2, etc. for this. In Projecteur, I want to put these hotkeys on the Logitech Spotlight presenter. 

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Ubuntu 22.04.1
 - Desktop/Window Manager and Version KDE 5.24.4
 - Did you built _Projecteur_ yourself?: `[y/n]` no
 - What is the output of `projecteur -f` ?: 
```
Projecteur 0.9.1
  - git-branch: tag: v0.9.2, master
  - git-hash: 82d9cfac1082a5cf28debb79a7be732fabf4dfd4
  - compiler: GNU 11.2.0
  - qt-version: (build: 5.15.2, runtime: 5.15.3)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])
```
 - What is the output of `projecteur -d` ?: ...
```
Projecteur 0.9.1; device scan

 * Found 1 supported devices. (1 readable, 1 writable)

 +++ name:     'Logitech USB Receiver'
     userName: 'Logitech Spotlight (USB)'
     vendorId:  046d
     productId: c53e
     phys:      usb-0000:00:14.0-4
     busType:   USB
     devices:   /dev/input/event20, /dev/input/event18, /dev/input/event19, /dev/hidraw2, /dev/input/event17
     readable:  true
     writable:  true
```

**Comment by jahnf** [comment] 2022-08-16 06:19
Thanks for reporting.

**Comment by jahnf** [comment] 2023-02-17 18:59
What kind of keyboard layout to you have? German I guess? 

Sadly I cannot reproduce this issue. Do you have more information?

Alt + Shift + 1 -- will end up being "Alt + Shift + !" on my system because I have a US layout. (Shift + 1 = !)

![image](https://user-images.githubusercontent.com/5852240/219759869-d100e55c-eb31-4b88-b025-f068c4146a55.png)

**Comment by jahnf** [comment] 2023-10-17 07:35
Closing this, not reproducible with current versions.

**Closed by jahnf** 2023-10-17 07:35 UTC
Labels: investigate
