### ISSUE TITLE
Package conflict in Fedora 33 stops install

### ISSUE THREAD

**Issue by BriggsyUK1970** [jahnf/Projecteur#122] opened 2021-02-22 15:03 UTC
**Description**
Installing version 0.9 for Fedora 33 fails on transaction test because of conflict with filesystem-3.14-3.fc33.x86_64

**To Reproduce**
My Fedora is a standard build made two weeks ago but my filesystems layout is maybe a bit individual, with a nvme disk with three partitions.
/ is btrfs
/boot ext4
/home is an encrypted xfs

**Expected behavior**
Package installs

**Desktop/Linux Environment (please complete the following information):**
 - Fedora 33 
 - GNOME 3.38.4 Wayland Windowing System
 - Did you built _Projecteur_ yourself?: `[y/n]` \
 I tried to install with #dnf install projecteur-0.9_fedora-33-x86_64.rpm
No output from projecteur as install failed 

**Screenshots**
file:///home/briggsy_uk/Pictures/projecteur-install-fail.png

**Comment by BriggsyUK1970** [comment] 2021-02-22 15:26
BTW projecteur-0.9-alpha.83_fedora-33-x86_64.rpm does install and start.

But some problems with window management and becoming a ghost process when I Esc from the UI when testing
[root@xxxxxx ~]# ps -ef|grep project
xxxxxx   44544    2931  1 15:15 ?        00:00:01 /usr/local/bin/projecteur
[root@xxxxxx ~]# projecteur on
Another application instance is already running. Exiting.

**Comment by jahnf** [comment] 2021-02-22 16:39
Hi @BriggsyUK1970, thanks for reporting  

for "2nd" your issue with the "ghost process" : Please have a look at the README about the missing system tray icon (fedora needs a GNOME plugin for it) - the "ghost process" is just not showing in the system tray is my guess.
You can send a quit command to the running instance with `projecteur -c quit`  // also see `projecteur --help-all` for all commands possible.  And you could also start projecteur with `--minimize-only` for a different behavior of the dialog.

for the 1st issue of the released 0.9 version:
can you please provide the output of you install command? (`dnf projecteur...`)

**Comment by BriggsyUK1970** [comment] 2021-02-23 10:19
[root@xxxx Downloads]# dnf install projecteur-0.9_fedora-33-x86_64.rpm
Last metadata expiration check: 0:40:34 ago on Tue 23 Feb 2021 09:37:08 GMT.
Dependencies resolved.
================================================================================
 Package            Architecture   Version           Repository            Size
================================================================================
Installing:
 projecteur         x86_64         0.9.0-.0          @commandline         282 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 282 k
Installed size: 712 k
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib from install of projecteur-0.9.0-.0.x86_64 conflicts with file from package filesystem-3.14-3.fc33.x86_64

**Comment by jahnf** [comment] 2021-02-24 11:26
It seems there is also something off with the version number in the generated packages (at least for the release version)
I need some time to investigate this further and look at all the created packages. Will be fixed on the current 1.0 alpha / develop branch, and I might create then a hotfix release 0.9.1

**Comment by BriggsyUK1970** [comment] 2021-02-24 11:29
Thanks so much, I really love the tool!

**Comment by lukas-miksicek** [comment] 2021-02-26 10:56
As far as i can tell, the problem is that the rpm contains directories ( that we can safely assume already exist on the fielsystem ) that are provided by different package (filesystem). So to fix this,  removing this directories from the rpm package should be enough:
/usr
/usr/lib
/usr/local
...

**Comment by jahnf** [comment] 2021-02-26 11:01
Hi @lukas-miksicek - yes thank you - I am using `CPack` that makes it possible for me to provide all these packages without being an expert in packaging :) but there is a setting to remove directories with `CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION`.
That should be an easy fix

The second thing I want to address within this issue is
that I saw the weird version number: `projecteur-0.9.0-.0.x86_64` in the log output of @BriggsyUK1970.

**Comment by jahnf** [comment] 2021-02-26 11:10
@BriggsyUK1970 Could you please verify that you can install the package from the ci build here https://github.com/jahnf/Projecteur/actions/runs/602522657 ? (Three is a fedora-33 package artifact attached to that build)
Thank you in advance.

In any case I will keep this issue open for adressing the issue with the generated version and when that is fixed also the creation of a bugfix release 0.9.1.

**Comment by lukas-miksicek** [comment] 2021-02-26 11:29
[root@cat tmp]# dnf install projecteur-1.0-alpha.3_fedora-33-x86_64.rpm 
jahnf-projecteur-stable                                                                                    445  B/s | 473  B     00:01    
jahnf-projecteur-stable-noarch                                                                             386  B/s | 473  B     00:01    
jahnf-projecteur-stable-source                                                                             788  B/s | 473  B     00:00    
Dependencies resolved.
===========================================================================================================================================
 Package                                  Architecture             Version                            Repository                      Size
===========================================================================================================================================
Installing:
 projecteur                               x86_64                   1.0.0-alpha.3                      @commandline                   282 k
Installing dependencies:
 qt5-qtgraphicaleffects                   x86_64                   5.15.2-2.fc33                      updates                        112 k

Transaction Summary
===========================================================================================================================================
Install  2 Packages

Total size: 394 k
Installed size: 1.3 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] qt5-qtgraphicaleffects-5.15.2-2.fc33.x86_64.rpm: Already downloaded                                                             
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib from install of projecteur-1.0.0-alpha.3.x86_64 conflicts with file from package filesystem-3.14-3.fc33.x86_64

**Comment by lukas-miksicek** [comment] 2021-02-26 11:46
/usr
/usr/lib
/usr/local
/usr/local/bin
/usr/local/share
/usr/local/share/applications
/usr/local/share/man
/usr/local/share/man/man1

This is complete list of duplicit dirs in the package

**Comment by jahnf** [comment] 2021-02-26 12:11
@lukas-miksicek Thanks. Results of https://github.com/jahnf/Projecteur/actions/runs/602669047 should work again. Please verify if you can. 

(issue with weird version for release builds still open)

**Comment by lukas-miksicek** [comment] 2021-02-26 14:33
Yes, it installs without a problem. Great. Thank You.

**Comment by jahnf** [comment] 2021-02-26 16:02
Fix is merged to develop, additional fixes for the version number and the package bugfix release 0.9.1 will be handled in #123

**Closed by jahnf** 2021-02-26 16:02 UTC
Labels: bug, build-system

**Comment by BriggsyUK1970** [comment] 2021-03-01 12:37
Confirmed... build 0.9.1-1 installed fine this AM
