### ISSUE TITLE
Spotlight does not stick the the cursor

### ISSUE THREAD

**Issue by nipser** [jahnf/Projecteur#21] opened 2019-06-12 09:38 UTC
OS: Debian 9.9 with gnome 3.22.3-3

When I hold upper button down, the spotlight appears. Unfortunatly, when moving the presenter, the spotlight barely moves and after some centimeters it just stops. The cursor appears and can be moves just as normal.
My self-compiled version 0.4 worked as expected.

Can you help? :/

Edit: I just tested version 0.4 again and it still works fine. When I compile 0.5 locally, the issue still persists.

![circle_does_not_stick](https://user-images.githubusercontent.com/11896495/59339436-7727e680-8d04-11e9-8d11-a3b85f1830cf.png)

**Comment by jahnf** [comment] 2019-06-12 10:22
Which version of _Projecteur_ are you running? (Self-built or linux package?)

**Comment by nipser** [comment] 2019-06-12 10:24
> Which version of _Projecteur_ are you running? (Self-built or linux package?)

I'm running projecteur-0.5_debian-9-x86_64.deb from bintray.

The version 0.4 I have (the one that works) is selfmade.

**Comment by jahnf** [comment] 2019-06-12 10:31
One Idea: When switching from the self-built version make sure you remove the udev rule file you copied to /etc/udev/rules.d as the package comes with one itself and I think the package puts it in something like /lib/udev/rules.d (on debian based systems at least).

So these rules might conflicting each other

**Comment by nipser** [comment] 2019-06-12 10:57
I removed the udev-rule-file. Sadly, the behaviour is still the same. 
I also tried building 0.5 myself now and get the same result.

**Comment by jahnf** [comment] 2019-06-12 11:06
After remove the other rule file, did you trigger a reload of the rules (`sudo udevadm control --reload-rules` and `sudo udevadm trigger`)  ? ...

If that does not work could you please _remove the deb package_  
and then try a self built version of 0.4 and 0.5 report what worked and what not? 
That would be helpful. Also: Is your spotlight connected via the dongle or bluetooth?

I'm running mostly Ubuntu (and OpenSuse at work), so cannot reproduce the issue right now.

**Comment by nipser** [comment] 2019-06-12 11:14
> After remove the other rule file, did you trigger a reload of the rules (`sudo udevadm control --reload-rules` and `sudo udevadm trigger`) ? ...

I did.

> If that does not work could you please _remove the deb package_
> and then try a self built version of 0.4 and 0.5 report what worked and what not?

-> apt purge projecteur

Working: self built version 0.4
Not working: self build version 0.5

> That would be helpful. Also: Is your spotlight connected via the dongle or bluetooth?

Dongle.

**Comment by jahnf** [comment] 2019-06-12 11:23
Well, then I'm out of quick ideas.. changes from 0.4 to 0.5 are not to drastic:
* additional spotlight shapes
* command line options
* and automated Linux package builds...

So nothing really ground breaking, you can stick with **0.4** until I have time to investigate the issue for the next minor release.

**Comment by nipser** [comment] 2019-06-12 11:30
Will do. Thank you for the quick investigation and for the tool in general :) I really love the spotlight-function!

For further investigation, I uploaded a video showing the problem again: https://youtu.be/u58F1D0hUL8

**Comment by jahnf** [comment] 2019-06-13 05:32
@nipser : Could you try a build of v0.5 / or the latest from develop but replace the file `qml/main.qml`
with the one from **v0.4** (https://github.com/jahnf/Projecteur/blob/v0.4/qml/main.qml)
(Spotlight shape settings won't have any effect then, but to narrow down the issue and see if this works on your machine)

**Comment by nipser** [comment] 2019-06-13 14:14
Done. Compiling works without any problem. When I use the Spotlight-function, this happens:

![Screenshot from 2019-06-13 16-08-59](https://user-images.githubusercontent.com/11896495/59439796-2db7c400-8df6-11e9-83f6-5f1664c408b7.png)

**Comment by jahnf** [comment] 2019-11-08 11:25
@nipser I cannot reproduce it. Is this issue still valid?
Does it have to do with a compositor not running? (see user comments in #10 #24 and #26)

**Comment by jahnf** [comment] 2019-11-10 18:38
Closing this issue. Not reproducible for me. If still valid you can reopen this issue.

**Closed by jahnf** 2019-11-10 18:38 UTC
Labels: investigate
